import type {
  CompanySettings,
  BusinessRules,
  ProductionConstants,
  PaintProduct,
  ProductionRates,
} from '@/types/settings'

export const DEFAULT_COMPANY: CompanySettings = {
  name: 'Vanhousing Painters LLC',
  phone: '253-656-2328',
  email: 'Vanhousingsales@gmail.com',
  website: 'www.vanhousingpainters.com',
  streetAddress: '17146 SE 248th Pl',
  cityStateZip: 'Covington, WA 98042',
}

export const DEFAULT_BUSINESS_RULES: BusinessRules = {
  wage: 30,
  payrollBurden: 1,
  netProfitMargin: 0.20,
  overheadMargin: 0.10,
  marketingMargin: 0.10,
  salesMargin: 0.07,
  productionMgmtMargin: 0.07,
  additionalMargin1: 0,
  additionalMargin2: 0,
  additionalMargin3: 0,
  additionalMargin4: 0,
  additionalMargin5: 0,
  depositPercent: 0.20,
  salesDiscount: 0.10,
  woodReplacementMinimum: 400,
  salesTax: 0.101,
}

export const DEFAULT_PRODUCTION_CONSTANTS: ProductionConstants = {
  paintCoverageSpray: 2,
  paintCoverageBrushRoll: 1.3,
  cleanupHoursRatio: 20,
  fasciaWidthIn: 18,
  eavesWidthIn: 24,
  otherTrimWidthIn: 4,
  railingsTrimRatio: 26,
  windowTrimWidthIn: 4,
  downspoutWidthIn: 12,
  shutterSqft: 6,
  stainCoverage: 1.3,
  sundriesPerHour: 1,
}

export const DEFAULT_PAINT_PRODUCTS: PaintProduct[] = [
  { id: 'sw-super-paint-flat',          name: '(SW) Super Paint Flat',                      singleGallon: 41.89, fiveGallon: 38.89, coverage: 400 },
  { id: 'sw-super-paint-satin',         name: '(SW) Super Paint Satin',                     singleGallon: 43.99, fiveGallon: 40.99, coverage: 400 },
  { id: 'sw-emerald-rr-flat',           name: '(SW) Emerald Rain Refresh Flat',              singleGallon: 69.99, fiveGallon: 66.99, coverage: 350 },
  { id: 'sw-emerald-rr-satin',          name: '(SW) Emerald Rain Refresh Satin',             singleGallon: 70.99, fiveGallon: 67.99, coverage: 350 },
  { id: 'sw-duration-flat',             name: '(SW) Duration Flat',                          singleGallon: 54.99, fiveGallon: 51.99, coverage: 350 },
  { id: 'sw-duration-satin',            name: '(SW) Duration Satin',                         singleGallon: 56.99, fiveGallon: 53.99, coverage: 350 },
  { id: 'sw-emerald-flat',              name: '(SW) Emerald Flat',                           singleGallon: 59.99, fiveGallon: 56.99, coverage: 350 },
  { id: 'sw-emerald-satin',             name: '(SW) Emerald Satin',                          singleGallon: 62.99, fiveGallon: 59.99, coverage: 350 },
  { id: 'sw-a100-flat',                 name: '(SW) A-100 Flat',                             singleGallon: 37.00, fiveGallon: 35.00, coverage: 400 },
  { id: 'sw-a100-satin',                name: '(SW) A-100 Satin',                            singleGallon: 39.00, fiveGallon: 37.00, coverage: 400 },
  { id: 'sw-super-deck-stain',          name: '(SW) Super Deck Stain',                       singleGallon: 38.49, fiveGallon: 36.49, coverage: 400 },
  { id: 'sw-woodscapes-stain',          name: '(SW) Woodscapes Stain',                       singleGallon: 42.19, fiveGallon: 40.19, coverage: 400 },
  { id: 'miller-evolution',             name: 'Miller Paint EVOLUTION',                      singleGallon: 40.00, fiveGallon: 40.00, coverage: 450 },
  { id: 'sw-sherlastic',               name: '(SW) SherLastic',                             singleGallon: 28.00, fiveGallon: 26.00, coverage: 100 },
  { id: 'sw-pro-dtm-acrylic',          name: '(SW) Pro Industrial DTM Acrylic',             singleGallon: 50.00, fiveGallon: 47.00, coverage: 270 },
  { id: 'sw-wood-primer-oil',          name: '(SW) Wood Primer Exterior Oil',               singleGallon: 33.00, fiveGallon: 33.00, coverage: 400 },
  { id: 'bm-ultra-spec-satin',         name: '(BM) Ultra Spec Satin',                       singleGallon: 43.00, fiveGallon: 43.00, coverage: 400 },
  { id: 'bm-regal-morgard',            name: '(BM) Regal Morgard Low Luster',               singleGallon: 70.00, fiveGallon: 70.00, coverage: 400 },
  { id: 'bm-regal-select-hb',          name: '(BM) Regal Select High Build Low Luster',     singleGallon: 70.00, fiveGallon: 70.00, coverage: 400 },
  { id: 'bm-aura-satin',               name: '(BM) Aura Satin',                             singleGallon: 80.00, fiveGallon: 80.00, coverage: 450 },
  { id: 'no-paint',                    name: 'No Paint (Client Providing Paint)',            singleGallon: 7.00,  fiveGallon: 7.00,  coverage: 400 },
  { id: 'masonry-sw-a100',             name: 'Masonry - (SW) A-100',                        singleGallon: 37.00, fiveGallon: 35.00, coverage: 350 },
  { id: 'masonry-sw-super-paint',      name: 'Masonry - (SW) Super Paint',                  singleGallon: 42.00, fiveGallon: 39.00, coverage: 350 },
  { id: 'masonry-sw-emerald-rr',       name: 'Masonry - (SW) Emerald Rain Refresh',         singleGallon: 70.00, fiveGallon: 67.00, coverage: 350 },
  { id: 'masonry-sw-duration',         name: 'Masonry - (SW) Duration',                     singleGallon: 55.00, fiveGallon: 52.00, coverage: 250 },
  { id: 'masonry-sw-emerald',          name: 'Masonry - (SW) Emerald',                      singleGallon: 60.00, fiveGallon: 57.00, coverage: 250 },
  { id: 'masonry-bm-ultra-spec',       name: 'Masonry - (BM) Ultra Spec',                   singleGallon: 43.00, fiveGallon: 43.00, coverage: 300 },
  { id: 'masonry-bm-regal-select',     name: 'Masonry - (BM) Regal Select',                 singleGallon: 70.00, fiveGallon: 70.00, coverage: 350 },
  { id: 'masonry-bm-aura',             name: 'Masonry - (BM) Aura',                         singleGallon: 80.00, fiveGallon: 80.00, coverage: 250 },
]

export const DEFAULT_RATES: ProductionRates = {
  prepWork: {
    powerWash:            1500,
    scrapeOneBoard:         40,
    scrapeSurface:         100,
    scuffSand:             100,
    lightSand:              50,
    heavySand:              25,
    primingBrushSqft:      150,
    primingBrushLnft:       60,
    scrapeSandPrimeLnft:    25,
    ssp75to100:             10,
    ssp50to75:              50,
    ssp25to50:             100,
    ssp25orLess:           200,
    sspLocalized:            6,
    caulking1Story:        100,
    caulking2Story:         75,
    caulking3Story:         35,
    manualPrepHours:         1,
    miscHazardHours:         1,
    managerUnits:            0,
  },
  bodyApplication: {
    sidingSpray:               200,
    sidingSprayBackroll:       150,
    sidingRoll:                125,
    masonrySpray:              150,
    masonrySprayBackroll:      125,
    masonryRoll:               100,
    sidingBrush:               100,
    masonryBrush:               75,
    oneCoatSidingSpray:        150,
    accentSidingSpray:         200,
    accentSidingSprayBackroll: 150,
    accentSidingRoll:          125,
    accentMasonrySpray:        150,
    accentMasonrySprayBackroll:125,
    accentMasonryRoll:         100,
    accentSidingBrush:         100,
    accentMasonryBrush:         75,
    stainingShakesBackbrush:   180,
  },
  eaves: {
    eavesBodyColor:          75,
    eavesTrimColor:          45,
    eavesSeparateColor:      35,
    eaves3rdBodyColor:       50,
    eaves3rdTrimColor:       10,
    eaves3rdSeparateColor:    5,
  },
  fascia: {
    fascia1Story:  40,
    fascia2Story:  35,
    fascia3Story:  15,
  },
  windows: {
    vinylNoTrim:           { unitsPerHr: 6,    trimLnFt: 0  },
    woodNoTrimBody:        { unitsPerHr: 2,    trimLnFt: 0  },
    vinylWithTrim:         { unitsPerHr: 2,    trimLnFt: 16 },
    woodDontOpen:          { unitsPerHr: 1,    trimLnFt: 32 },
    woodOpen:              { unitsPerHr: 2/3,  trimLnFt: 40 },
    threeDVinyl:           { unitsPerHr: 1,    trimLnFt: 20 },
    threeDWoodDontOpen:    { unitsPerHr: 0.8,  trimLnFt: 36 },
    threeDWoodOpen:        { unitsPerHr: 0.57, trimLnFt: 44 },
    twoToneWoodDontOpen:   { unitsPerHr: 2/3,  trimLnFt: 32 },
    twoToneWoodOpen:       { unitsPerHr: 0.5,  trimLnFt: 40 },
    threeD2ToneWoodDontOpen:{ unitsPerHr: 0.57, trimLnFt: 36 },
    threeD2ToneWoodOpen:   { unitsPerHr: 0.44, trimLnFt: 44 },
  },
  otherTrim: {
    otherTrim1Story:            40,
    otherTrim2PlusStory:        35,
    downspoutsPosts:            20,
    trim3D:                     20,
    tudorTrimFacing:            50,
    tudorTrim3D:                30,
    removeReinstallDownspouts:  20,
    justRemoveDownspouts:       60,
  },
  doors: {
    bodyColorNoTrim:        { unitsPerHr: 4,    trimLnFt: 0   },
    bodyColorWithTrim:      { unitsPerHr: 2/3,  trimLnFt: 35  },
    trimColorNoTrim:        { unitsPerHr: 2/3,  trimLnFt: 70  },
    trimColorWithTrim:      { unitsPerHr: 0.5,  trimLnFt: 105 },
    accentColorNoTrim:      { unitsPerHr: 0.5,  trimLnFt: 70  },
    accentColorWithTrim:    { unitsPerHr: 0.4,  trimLnFt: 105 },
    stainedToPaintedNoTrim: { unitsPerHr: 0.4,  trimLnFt: 70  },
    stainedToPaintedWithTrim:{ unitsPerHr: 0.36, trimLnFt: 105 },
  },
  sidelights: {
    bodyColorNoTrim:        { unitsPerHr: 8,    trimLnFt: 0  },
    bodyColorWithTrim:      { unitsPerHr: 8/3,  trimLnFt: 25 },
    trimColorNoTrim:        { unitsPerHr: 8/3,  trimLnFt: 35 },
    trimColorWithTrim:      { unitsPerHr: 2,    trimLnFt: 60 },
    accentColorNoTrim:      { unitsPerHr: 8/3,  trimLnFt: 35 },
    accentColorWithTrim:    { unitsPerHr: 1.6,  trimLnFt: 60 },
    stainedToPaintedNoTrim: { unitsPerHr: 1.14, trimLnFt: 35 },
    stainedToPaintedWithTrim:{ unitsPerHr: 0.73, trimLnFt: 60 },
  },
  garageDoors: {
    singleBodyColor:          { unitsPerHr: 1,    trimLnFt: 50  },
    singleBodyColorWindows:   { unitsPerHr: 0.8,  trimLnFt: 50  },
    singleTrimColor:          { unitsPerHr: 2/3,  trimLnFt: 265 },
    singleTrimColorWindows:   { unitsPerHr: 0.57, trimLnFt: 265 },
    singleAccentColor:        { unitsPerHr: 2/3,  trimLnFt: 265 },
    singleAccentColorWindows: { unitsPerHr: 0.57, trimLnFt: 265 },
    doubleBodyColor:          { unitsPerHr: 2/3,  trimLnFt: 70  },
    doubleBodyColorWindows:   { unitsPerHr: 0.5,  trimLnFt: 70  },
    doubleTrimColor:          { unitsPerHr: 0.44, trimLnFt: 500 },
    doubleTrimColorWindows:   { unitsPerHr: 0.36, trimLnFt: 500 },
    doubleAccentColor:        { unitsPerHr: 0.44, trimLnFt: 500 },
    doubleAccentColorWindows: { unitsPerHr: 0.36, trimLnFt: 500 },
  },
  railings: {
    railings1Color:    5,
    railings2ColorEasy: 4,
    railings2ColorHard: 2,
  },
  shutters: {
    accentGround: 4,
    accentLadder: 2,
    trimGround:   4,
    trimLadder:   2,
  },
  staining: {
    deckSolidStain:       { rate: 100,  surfaceAreaFactor: 1     },
    stairsSolidStain:     { rate: 4,    surfaceAreaFactor: 10    },
    fenceFlatSpray:       { rate: 20,   surfaceAreaFactor: 5     },
    fenceBeamsSpray:      { rate: 17.5, surfaceAreaFactor: 5     },
    fenceFlatBrushRoll:   { rate: 10,   surfaceAreaFactor: 5     },
    fenceBeamsBrushRoll:  { rate: 6,    surfaceAreaFactor: 5     },
    stainRailings:        { rate: 5,    surfaceAreaFactor: 8.667 },
    stainPosts:           { rate: 20,   surfaceAreaFactor: 1.333 },
    stainTrim:            { rate: 35,   surfaceAreaFactor: 0.333 },
  },
  woodReplacement: {
    trim1Story:             6.84,
    trim2Story:             7.57,
    regularSiding1Story:    9.00,
    regularSiding2Story:   10.00,
    cementFiber1Story:      8.00,
    cementFiber2Story:      9.50,
    doorFrame:            113.48,
    fascia1Story:          18.00,
    fascia2Story:          11.85,
    fascia1StoryGutter:    19.00,
    fascia2StoryGutter:    22.00,
    railings:               9.20,
    eaveSoffit1Story:      25.20,
    eaveSoffit2Story:      28.30,
    hardieBoard:           11.30,
  },
}
